### ISSUE TITLE
Tracking list of bugs/enhancements for future releases

### ISSUE THREAD

**Issue by PeterBowman** [asrob-uc3m/ZBar#1]
- [ ] Replace current `.gitignore` with `.hgignore`'s contents? (a8f53d5)
- [ ] Restore `-Werror` flag and fix warnings? (506fe34)
- [ ] Fix doc generation (5c2342b, ebfe15f)
- [ ] do we really need `libwinpthread-1.dll` (official releases shipped without this)? (4fd03b9)
- [ ] Link gcc and standard C library statically? (298b6a4)
- [ ] Read NSIS installer options from the command line? (a2bd66c)
- [ ] Compile with remaining *standard* dependencies? (403c212)
- AppVeyor CI goodies:
  - [ ] Compile full project
  - [ ] Compile and run tests?
  - [ ] Create deploy rules
